### ISSUE TITLE
Adding more than one co-author removes the existing one

### ISSUE THREAD

**Issue by tgkenney-dsg** [hawser86/co-author-plugin#3]
Right now the plugin seems to remove any existing co-author lines when adding more.  Can we get the plugin to support adding multiple co-authors such as shown on the [help page](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) 

![image](https://user-images.githubusercontent.com/59695082/72461573-50032d00-379d-11ea-9038-2a0255a4601f.png)

**Comment by hawser86** [comment]
The plugin replaces any previous co-author from the commit message. You can however add more names in one step. 
Select "More options" at the bottom of the co-author list, then select more authors using the checkboxes, then finally click OK.
Is this solution satisfying?

**Comment by tgkenney-dsg** [comment]
I wasn't aware you could use the check boxes there, that does work for us.  I do think that it might be more user friendly if the check boxes could be moved outside of that menu as well.  So that when the icon is clicked during the commit message, the list of co-authors could show with either single select  as it does now, or using checkboxes beside each name
